"""remove mtest table

Revision ID: b1981c757758
Revises: 4b08a4caf9e0
Create Date: 2021-12-21 15:12:15.397077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1981c757758'
down_revision = '4b08a4caf9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mtest_id', table_name='mtest')
    op.drop_table('mtest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='mtest_pkey'),
    sa.UniqueConstraint('email', name='mtest_email_key')
    )
    op.create_index('ix_mtest_id', 'mtest', ['id'], unique=False)
    # ### end Alembic commands ###
